/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot API
 * Chatbot server interface to handle a conversation
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FlowValue,
} from '../models';
import {
    FlowValueFromJSON,
    FlowValueToJSON,
} from '../models';

export interface PostConversationRequest {
    flowValue?: Array<FlowValue>;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * saves the whole conversation
     */
    async postConversationRaw(requestParameters: PostConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/conversation`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.flowValue.map(FlowValueToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * saves the whole conversation
     */
    async postConversation(requestParameters: PostConversationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postConversationRaw(requestParameters, initOverrides);
    }

}
