/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot API
 * Chatbot server interface to handle a conversation
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type FlowValueType
 * 
 * @export
 */
export type FlowValueType = boolean | number | string;

export function FlowValueTypeFromJSON(json: any): FlowValueType {
    return FlowValueTypeFromJSONTyped(json, false);
}

export function FlowValueTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowValueType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...booleanFromJSONTyped(json, true), ...numberFromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function FlowValueTypeToJSON(value?: FlowValueType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }
    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

