/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot API
 * Chatbot server interface to handle a conversation
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FlowValueType } from './FlowValueType';
import {
    FlowValueTypeFromJSON,
    FlowValueTypeFromJSONTyped,
    FlowValueTypeToJSON,
} from './FlowValueType';

/**
 * 
 * @export
 * @interface FlowValue
 */
export interface FlowValue {
    /**
     * 
     * @type {string}
     * @memberof FlowValue
     */
    name: string;
    /**
     * 
     * @type {FlowValueType}
     * @memberof FlowValue
     */
    value: FlowValueType;
}

/**
 * Check if a given object implements the FlowValue interface.
 */
export function instanceOfFlowValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function FlowValueFromJSON(json: any): FlowValue {
    return FlowValueFromJSONTyped(json, false);
}

export function FlowValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': FlowValueTypeFromJSON(json['value']),
    };
}

export function FlowValueToJSON(value?: FlowValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': FlowValueTypeToJSON(value.value),
    };
}

